### ISSUE TITLE
Some of the plugins does not work then integrated with maven

### ISSUE THREAD

**Issue by rlazdauskas** [walkmod/maven-walkmod-plugin#1]
Hi,

I have added maven plugin to projects pom.xml and added Checkstyle, Pmd, Dead-code-cleaner, Override plugins to walkmod.xml. Then I try to run "walkmod apply -e" they work, but then i write "mvn clean install" the following error appears:
        ---------------------------------------------------------------------
##  INFO [main] - *\* STARTING TRANSFORMATIONS CHAINS **

[ERROR] Error executing Maven.
[ERROR] Unable to create injector, see the following errors:

1) No scope is bound to org.apache.maven.SessionScoped.
  at org.apache.maven.ReactorReader.class(Unknown Source)
  at ClassRealm[plexus.core, parent: null](via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)

1 error
 INFO [main] - TRANSFORMATION CHAIN FAILS

(import-cleaner, license-applier works correctly with mvn clean install)

[pmd.xml.txt](https://github.com/walkmod/maven-walkmod-plugin/files/250004/pmd.xml.txt)
[pom.xml.txt](https://github.com/walkmod/maven-walkmod-plugin/files/250006/pom.xml.txt)
[walkmod.xml.txt](https://github.com/walkmod/maven-walkmod-plugin/files/250005/walkmod.xml.txt)

**Comment by rpau** [comment]
Hi, thanks for reporting the issue. 

I saw your email, but I couldn't analyze what it happens yet. I would try it tomorrow.

Thanks again for your feedback.

**Comment by rpau** [comment]
Hi,

This problem was caused because the classloader of maven overrides the classes of the embedded maven of the walkmod-maven-plugin. I have fixed it into the walkmod-maven-plugin analyzing if the system contains a maven installation, in that case, uses such installation instead of the embedeed maven to build "compile" the project.

I have deployed a new version into the Maven central repository: walkmod-maven-plugin-2.1.3
In 1 hour, it should be available. So, if you can clean the .ivy directory (.ivy2/cache/org.walkmod/walkmod-maven-plugin), the system will be upgraded.
